# Site
# repository: sproogen/resume-theme
repository: ricyoung/ricyoung.github.io


favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Richard Young
title: Senior Data Scientist
email: data4ric@gmail.com
website: https://ricyoung.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: DataRichNerd1
github_username:  ricyoung
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: richard-j-young/
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-1109-7552

# Additional icon links
additional_links:
- title: Download PDF
  icon: fas fa-file-pdf
  url: https://www.dropbox.com/resume
  
  title: Summary Resume
  icon: fas fa-sigma
  url: https://www.dropbox.com/resume

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/sm.gif
about_content: | # this will include new lines to allow paragraphs
 Research Data Scientist with years of experience in healthcare and data analysis looking to work with progressive companies to solve operational and data analytical challenges. Achievements include designing and supporting a large HPC cluster for research and business intelligence purposes, utilized multi data sources to discover new actionable knowledge and reducing operational costs. Highly skilled in hypothesis testing, analytical process management, visual problem solving, and data story telling.

  I am most skilled in: <mark>Problem Solving using Data</mark> and <mark>Overlanding</mark>

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Optum
        link: https://www.optum.com/
        # link_text: boringcompany.com
        sub_title: Senior Data Scientist
        caption: March 2022 - Present
        quote:  Fusing Clinical Decision Support with multi data sources and multi lines of business to reduce cost and increase patients access to health care.
          
        description: | # this will include new lines to allow paragraphs
            <br>• Apply advanced statistical and predictive modeling techniques to data related to the optimization of healthcare and patient experiences
            <br>• Propose innovative new ways to look at problems using data, statistical analysis and machine learning
            <br>• Communicate findings, verbally, and visually, to senor leadership, business partners, and clients
            <br>• Find out new data sources and verify integrity of data then fill gaps and improve models and business intellgenices 
            <br>• Support business needs around analytics, predictive modeling, and business intelligence
            <br>• Provide on-going tracking and monitoring of performance of statistical models and recommend ongoing improvements to methods and algorithms
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: ricyoung/ricyoung.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
