# Site
# repository: sproogen/resume-theme
repository: ricyoung/ricyoung.github.io


favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Richard Young
title: Senior Data Scientist
email: data4ric@gmail.com
website: https://ricyoung.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: DataRichNerd1
github_username:  ricyoung
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: richard-j-young/
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-1109-7552

# Additional icon links
additional_links:
- title: Download PDF
  icon: fas fa-file-pdf
  url: https://www.dropbox.com/resume
  
  title: Summary Resume
  icon: fas fa-sigma
  url: https://www.dropbox.com/resume

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/sm.gif
about_content: | # this will include new lines to allow paragraphs
 Research Data Scientist with years of experience in healthcare and data analysis looking to work with progressive companies to solve operational and data analytical challenges. Achievements include designing and supporting a large HPC cluster for research and business intelligence purposes, utilized multi data sources to discover new actionable knowledge and reducing operational costs. Highly skilled in hypothesis testing, analytical process management, visual problem solving, and data story telling.

  I am most skilled in: <mark>Problem Solving using Data</mark> and <mark>Overlanding</mark>
